Repository livekit/server-sdk-go, pull requests merged in 2025-10, with the labels that each got.

#750 Use the local variable for lastTS.
  pkg/synchronizer/track.go
Labels: slack-ts:cs-devs:1759335561.080819

#751 Add stats for packets and sender reports
  pkg/synchronizer/track.go
Labels: slack-ts:cs-devs:1759384297.994029

#752 Set initial PTS to estimated PTS to absorb pipeline start latency.
  pkg/synchronizer/track.go
Labels: slack-ts:cs-devs:1759395764.268439

#755 Use packet receive time to calculate PTS.
  pkg/synchronizer/track.go
  pkg/synchronizer/track_test.go
Labels: slack-ts:cs-devs:1759483512.284459

#762 Initialize should be called with the packet reception time
  pkg/synchronizer/track.go
  pkg/synchronizer/track_test.go
Labels: slack-ts:cs-devs:1759921039.301819
